const data = [
  {
    name: "D.Va",
    icon: "icons/vanguard/D.Va.webp",
    role: "vanguard",
    counterpicks: [
      "Zarya",
      "Sigma",
      "Roadhog",
      "Sombra",
      "Symmetra",
      "Tracer",
      "Baptiste",
      "Zenyatta",
      "Brigitte",
    ],
  },
  {
    name: "Doomfist",
    icon: "icons/vanguard/Doomfist.webp",
    role: "vanguard",
    counterpicks: [
      "Roadhog",
      "Orisa",
      "Reinhardt",
      "Sombra",
      "Pharah",
      "Reaper",
      "Ana",
      "Brigitte",
      "Mercy",
    ],
  },
  {
    name: "Junker Queen",
    icon: "icons/vanguard/Junker_Queen.webp",
    role: "vanguard",
    counterpicks: [
      "Reinhardt",
      "Zarya",
      "Sigma",
      "Ashe",
      "Sojourn",
      "Widowmaker",
      "Lucio",
      "Kiriko",
      "Ana",
    ],
  },
  {
    name: "Orisa",
    icon: "icons/vanguard/Orisa.webp",
    role: "vanguard",
    counterpicks: [
      "Zarya",
      "Sigma",
      "Junker Queen",
      "Pharah",
      "Ashe",
      "Widowmaker",
      "Baptiste",
      "Lucio",
      "Zenyatta",
    ],
  },
  {
    name: "Ramattra",
    icon: "icons/vanguard/Ramattra.webp",
    role: "vanguard",
    counterpicks: [
      "Orisa",
      "Winston",
      "Mauga",
      "Reaper",
      "Tracer",
      "Pharah",
      "Ana",
      "Kiriko",
      "Lucio",
    ],
  },
  {
    name: "Mauga",
    icon: "icons/vanguard/Mauga.webp",
    role: "vanguard",
    counterpicks: [
      "Zarya",
      "Wrecking Ball",
      "Mauga",
      "Sombra",
      "Echo",
      "Pharah",
      "Zenyatta",
      "Kiriko",
      "Lucio",
    ],
  },
  {
    name: "Reinhardt",
    icon: "icons/vanguard/Reinhardt.webp",
    role: "vanguard",
    counterpicks: [
      "Orisa",
      "Wrecking Ball",
      "Winston",
      "Sojourn",
      "Sombra",
      "Symmetra",
      "Kiriko",
      "Lucio",
      "Ana",
    ],
  },
  {
    name: "Roadhog",
    icon: "icons/vanguard/Roadhog.webp",
    role: "vanguard",
    counterpicks: [
      "Zarya",
      "Sigma",
      "Orisa",
      "Reaper",
      "Hanzo",
      "Pharah",
      "Ana",
      "Zenyatta",
      "Kiriko",
    ],
  },
  {
    name: "Sigma",
    icon: "icons/vanguard/Sigma.webp",
    role: "vanguard",
    counterpicks: [
      "Zarya",
      "Winston",
      "Junker Queen",
      "Sombra",
      "Pharah",
      "Echo",
      "Lucio",
      "Zenyatta",
      "Brigitte",
    ],
  },
  {
    name: "Winston",
    icon: "icons/vanguard/Winston.webp",
    role: "vanguard",
    counterpicks: [
      "Roadhog",
      "D.Va",
      "Junker Queen",
      "Reaper",
      "Sojourn",
      "Echo",
      "Ana",
      "Zenyatta",
      "Mercy",
    ],
  },
  {
    name: "Wrecking Ball",
    icon: "icons/vanguard/Wrecking_Ball.webp",
    role: "vanguard",
    counterpicks: [
      "Roadhog",
      "D.Va",
      "Doomfist",
      "Sombra",
      "Reaper",
      "Mei",
      "Ana",
      "Lucio",
      "Brigitte",
    ],
  },
  {
    name: "Zarya",
    icon: "icons/vanguard/Zarya.webp",
    role: "vanguard",
    counterpicks: [
      "Winston",
      "Wrecking Ball",
      "Reinhardt",
      "Widowmaker",
      "Tracer",
      "Pharah",
      "Lucio",
      "Zenyatta",
      "Brigitte",
    ],
  },
  {
    name: "Ashe",
    icon: "icons/duelist/Ashe.webp",
    role: "duelist",
    counterpicks: [
      "Sigma",
      "Winston",
      "Doomfist",
      "Widowmaker",
      "Hanzo",
      "Sojourn",
      "Ana",
      "Mercy",
      "Zenyatta",
    ],
  },
  {
    name: "Bastion",
    icon: "icons/duelist/Bastion.webp",
    role: "duelist",
    counterpicks: [
      "D.Va",
      "Sigma",
      "Orisa",
      "Sojourn",
      "Hanzo",
      "Tracer",
      "Zenyatta",
      "Lucio",
      "Kiriko",
    ],
  },
  {
    name: "Cassidy",
    icon: "icons/duelist/Cassidy.webp",
    role: "duelist",
    counterpicks: [
      "Sigma",
      "Roadhog",
      "Orisa",
      "Widowmaker",
      "Hanzo",
      "Sojourn",
      "Zenyatta",
      "Baptiste",
      "Kiriko",
    ],
  },
  {
    name: "Echo",
    icon: "icons/duelist/Echo.webp",
    role: "duelist",
    counterpicks: [
      "D.Va",
      "Roadhog",
      "Ramattra",
      "Ashe",
      "Soldier: 76",
      "Widowmaker",
      "Mercy",
      "Ana",
      "Baptiste",
    ],
  },
  {
    name: "Genji",
    icon: "icons/duelist/Genji.webp",
    role: "duelist",
    counterpicks: [
      "Winston",
      "Zarya",
      "Roadhog",
      "Pharah",
      "Torbjorn",
      "Cassidy",
      "Lucio",
      "Moira",
      "Kiriko",
    ],
  },
  {
    name: "Hanzo",
    icon: "icons/duelist/Hanzo.webp",
    role: "duelist",
    counterpicks: [
      "Sigma",
      "D.Va",
      "Doomfist",
      "Pharah",
      "Echo",
      "Tracer",
      "Mercy",
      "Zenyatta",
      "Lucio",
    ],
  },
  {
    name: "Junkrat",
    icon: "icons/duelist/Junkrat.webp",
    role: "duelist",
    counterpicks: [
      "D.Va",
      "Zarya",
      "Orisa",
      "Pharah",
      "Echo",
      "Widowmaker",
      "Baptiste",
      "Kiriko",
      "Ana",
    ],
  },
  {
    name: "Mei",
    icon: "icons/duelist/Mei.webp",
    role: "duelist",
    counterpicks: [
      "Doomfist",
      "Winston",
      "Orisa",
      "Pharah",
      "Hanzo",
      "Widowmaker",
      "Baptiste",
      "Kiriko",
      "Zenyatta",
    ],
  },
  {
    name: "Pharah",
    icon: "icons/duelist/Pharah.webp",
    role: "duelist",
    counterpicks: [
      "D.Va",
      "Wrecking Ball",
      "Ramattra",
      "Echo",
      "Widowmaker",
      "Soldier: 76",
      "Mercy",
      "Baptiste",
      "Ana",
    ],
  },
  {
    name: "Reaper",
    icon: "icons/duelist/Reaper.webp",
    role: "duelist",
    counterpicks: [
      "Zarya",
      "Orisa",
      "Reinhardt",
      "Pharah",
      "Echo",
      "Ashe",
      "Lucio",
      "Ana",
      "Brigitte",
    ],
  },
  {
    name: "Sojourn",
    icon: "icons/duelist/Sojourn.webp",
    role: "duelist",
    counterpicks: [
      "D.Va",
      "Doomfist",
      "Orisa",
      "Widowmaker",
      "Hanzo",
      "Genji",
      "Mercy",
      "Lucio",
      "Baptiste",
    ],
  },
  {
    name: "Soldier: 76",
    icon: "icons/duelist/Soldier_76.webp",
    role: "duelist",
    counterpicks: [
      "Doomfist",
      "Winston",
      "D.Va",
      "Widowmaker",
      "Hanzo",
      "Ashe",
      "Zenyatta",
      "Ana",
      "Lucio",
    ],
  },
  {
    name: "Sombra",
    icon: "icons/duelist/Sombra.webp",
    role: "duelist",
    counterpicks: [
      "Zarya",
      "Winston",
      "Junker Queen",
      "Hanzo",
      "Sojourn",
      "Torbjorn",
      "Ana",
      "Kiriko",
      "Brigitte",
    ],
  },
  {
    name: "Symmetra",
    icon: "icons/duelist/Symmetra.webp",
    role: "duelist",
    counterpicks: [
      "Roadhog",
      "Zarya",
      "Orisa",
      "Sombra",
      "Pharah",
      "Echo",
      "Lucio",
      "Mercy",
      "Moira",
    ],
  },
  {
    name: "Torbjorn",
    icon: "icons/duelist/Torbjorn.webp",
    role: "duelist",
    counterpicks: [
      "Orisa",
      "Sigma",
      "Roadhog",
      "Hanzo",
      "Soldier: 76",
      "Pharah",
      "Lucio",
      "Zenyatta",
      "Kiriko",
    ],
  },
  {
    name: "Tracer",
    icon: "icons/duelist/Tracer.webp",
    role: "duelist",
    counterpicks: [
      "Roadhog",
      "Orisa",
      "Doomfist",
      "Torbjorn",
      "Soldier: 76",
      "Ashe",
      "Kiriko",
      "Baptiste",
      "Moira",
    ],
  },
  {
    name: "Venture",
    icon: "icons/duelist/Venture.webp",
    role: "duelist",
    counterpicks: [
      "D.Va",
      "Orisa",
      "Zarya",
      "Junkrat",
      "Pharah",
      "Ashe",
      "Kiriko",
      "Ana",
      "Baptiste",
    ],
  },
  {
    name: "Widowmaker",
    icon: "icons/duelist/Widowmaker.webp",
    role: "duelist",
    counterpicks: [
      "Wrecking Ball",
      "Winston",
      "Sigma",
      "Genji",
      "Tracer",
      "Sombra",
      "Lucio",
      "Mercy",
      "Kiriko",
    ],
  },
  {
    name: "Ana",
    icon: "icons/strategist/Ana.webp",
    role: "strategist",
    counterpicks: [
      "D.Va",
      "Zarya",
      "Sigma",
      "Widowmaker",
      "Hanzo",
      "Sojourn",
      "Kiriko",
      "Lucio",
      "Baptiste",
    ],
  },
  {
    name: "Baptiste",
    icon: "icons/strategist/Baptiste.webp",
    role: "strategist",
    counterpicks: [
      "Wrecking Ball",
      "Doomfist",
      "Winston",
      "Hanzo",
      "Ashe",
      "Widowmaker",
      "Zenyatta",
      "Lucio",
      "Kiriko",
    ],
  },
  {
    name: "Brigitte",
    icon: "icons/strategist/Brigitte.webp",
    role: "strategist",
    counterpicks: [
      "Reinhardt",
      "Zarya",
      "Sigma",
      "Pharah",
      "Soldier: 76",
      "Sojourn",
      "Lucio",
      "Moira",
      "Zenyatta",
    ],
  },
  {
    name: "Illari",
    icon: "icons/strategist/Illari.webp",
    role: "strategist",
    counterpicks: [
      "D.Va",
      "Doomfist",
      "Winston",
      "Cassidy",
      "Hanzo",
      "Mei",
      "Ana",
      "Kiriko",
      "Lucio",
    ],
  },
  {
    name: "Kiriko",
    icon: "icons/strategist/Kiriko.webp",
    role: "strategist",
    counterpicks: [
      "Sigma",
      "Wrecking Ball",
      "Winston",
      "Hanzo",
      "Sojourn",
      "Echo",
      "Moira",
      "Brigitte",
      "Zenyatta",
    ],
  },
  {
    name: "Lifeweaver",
    icon: "icons/strategist/Lifeweaver.webp",
    role: "strategist",
    counterpicks: [
      "Winston",
      "Doomfist",
      "D.Va",
      "Ashe",
      "Pharah",
      "Widowmaker",
      "Ana",
      "Baptiste",
      "Moira",
    ],
  },
  {
    name: "Lucio",
    icon: "icons/strategist/Lucio.webp",
    role: "strategist",
    counterpicks: [
      "Roadhog",
      "Winston",
      "Doomfist",
      "Sombra",
      "Pharah",
      "Cassidy",
      "Moira",
      "Kiriko",
      "Mercy",
    ],
  },
  {
    name: "Mercy",
    icon: "icons/strategist/Mercy.webp",
    role: "strategist",
    counterpicks: [
      "D.Va",
      "Roadhog",
      "Wrecking Ball",
      "Soldier: 76",
      "Cassidy",
      "Tracer",
      "Ana",
      "Baptiste",
      "Moira",
    ],
  },
  {
    name: "Moira",
    icon: "icons/strategist/Moira.webp",
    role: "strategist",
    counterpicks: [
      "Roadhog",
      "Reinhardt",
      "Zarya",
      "Sombra",
      "Pharah",
      "Widowmaker",
      "Ana",
      "Baptiste",
      "Zenyatta",
    ],
  },
  {
    name: "Zenyatta",
    icon: "icons/strategist/Zenyatta.webp",
    role: "strategist",
    counterpicks: [
      "Junker Queen",
      "Reinhardt",
      "Doomfist",
      "Sombra",
      "Tracer",
      "Widowmaker",
      "Ana",
      "Lucio",
      "Mercy",
    ],
  },
];

export default data;
