export const HEROES = [
	{ id: 1, name: 'Bruce Banner', class: 'vanguard' },
	{ id: 2, name: 'Captain America', class: 'vanguard' },
	{ id: 3, name: 'Doctor Strange', class: 'vanguard' },
	{ id: 4, name: 'Groot', class: 'vanguard' },
	{ id: 5, name: 'Magneto', class: 'vanguard' },
	{ id: 6, name: 'Peni Parker', class: 'vanguard' },
	{ id: 7, name: 'Thor', class: 'vanguard' },
	{ id: 8, name: 'Venom', class: 'vanguard' },
	{ id: 9, name: 'Black Panther', class: 'duelist' },
	{ id: 10, name: 'Black Widow', class: 'duelist' },
	{ id: 11, name: 'Hawkeye', class: 'duelist' },
	{ id: 12, name: 'Hela', class: 'duelist' },
	{ id: 13, name: 'Iron Fist', class: 'duelist' },
	{ id: 14, name: 'Iron Man', class: 'duelist' },
	{ id: 15, name: 'Magik', class: 'duelist' },
	{ id: 16, name: 'Moon Knight', class: 'duelist' },
	{ id: 17, name: 'Namor', class: 'duelist' },
	{ id: 18, name: 'Psylocke', class: 'duelist' },
	{ id: 19, name: 'Scarlet Witch', class: 'duelist' },
	{ id: 20, name: 'Spider-Man', class: 'duelist' },
	{ id: 21, name: 'Squirrel Girl', class: 'duelist' },
	{ id: 22, name: 'Star-Lord', class: 'duelist' },
	{ id: 23, name: 'Storm', class: 'duelist' },
	{ id: 24, name: 'The Punisher', class: 'duelist' },
	{ id: 25, name: 'Winter Soldier', class: 'duelist' },
	{ id: 26, name: 'Wolverine', class: 'duelist' },
	{ id: 27, name: 'Adam Warlock', class: 'strategist' },
	{ id: 28, name: 'Cloak & Dagger', class: 'strategist' },
	{ id: 29, name: 'Jeff the Land Shark', class: 'strategist' },
	{ id: 30, name: 'Loki', class: 'strategist' },
	{ id: 31, name: 'Luna Snow', class: 'strategist' },
	{ id: 32, name: 'Mantis', class: 'strategist' },
	{ id: 33, name: 'Rocket Raccoon', class: 'strategist' },
	{ id: 34, name: 'Invisible Woman', class: 'strategist' },
	{ id: 35, name: 'Mister Fantastic', class: 'duelist' }
];
